---
version: 3
images:
  base_image:
    # name: quay.io/ansible/ansible-runner:stable-2.10-devel:latest
    # name: registry.hub.docker.com/alpinelinux/ansible:latest
    name: registry.hub.docker.com/rockylinux/rockylinux:latest
    # name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
    galaxy: ansible-collections.yml
    python: python-packages.txt
    ansible_core:
      package_pip: ansible==2.16.0
    ansible_runner:
      package_pip: ansible-runner==2.4.0

additional_build_files:
    # Can be used to resolve collections from private automation hub
    - src: ansible.cfg
      dest: configs

options:
    package_manager_path: /usr/bin/microdnf

additional_build_steps:
    prepend_base:
        - RUN $PYCMD -m pip install --upgrade pip setuptools
    prepend_galaxy:
        # Add custom ansible.cfg which defines collection install sources
        - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
        # AH_TOKEN is passed into the build command using a --build-arg
        # accept this as an ARG during this stage to reference later
        - ARG AH_TOKEN
        # Use the above ARG to define an environment variable holding
        # the token for resolving private collections
        - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN=$AH_TOKEN
